--CREATE DATABASE AB201
USE AB201
CREATE TABLE Regions (
Region_Id  INT PRIMARY KEY,
Region_Name NVARCHAR (25)
)

CREATE TABLE COUNTRIES (
COUNTRY_ID CHAR(2)PRIMARY KEY,
COUNTRY_NAME VARCHAR (40),
Region_Id INT
)
CREATE TABLE LOCATIONS(
LOCATION_ID INT PRIMARY KEY,
STREET_ADDRESS VARCHAR (25),
POSTAL_CODE VARCHAR(12),
CITY VARCHAR(30),
STATE_PROVINCE VARCHAR (12),
COUNTRY_ID CHAR(2)
)
CREATE TABLE DEPARTMENTS(
DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(30),
MANAGER_ID INT,
LOCATION_ID INT
)
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(25),
EMAIL VARCHAR(25),
PHONE_NUMBER VARCHAR(20),
HIRE_DATE DATE,
JOB_ID VARCHAR(10),
Salary INT,
COMMISSION_PCT INT,
MANAGER_ID INT,
DEPARTMENT_ID INT
)
CREATE TABLE JOBS(
JOB_ID VARCHAR(10),
JOB_TITLE VARCHAR(35),
MIN_SALARY INT,
MAX_SALARY INT,
)
CREATE TABLE JOBS_HISTORY(
EMPLOYEE_ID INT,
START_DATE DATE,
END_DATE DATE,
JOB_ID VARCHAR,
DEPARTMENT_ID INT
)
CREATE TABLE JOBS_GRADES(
GRADE_LEVEL VARCHAR (2),
LOWEST_SAL INT,
HIGHEST_SAL INT
)